name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
          - 4510-4559:4510-4559
        env:
          DEBUG: 1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
      - run: uv sync --locked
      - run: uv run -m unittest discover ./tests
        env:
          AWS_REGION: us-east-1
          AWS_ENDPOINT_URL: http://localstack:4566
      - run: uv run mypy -p sqla
      - run: uv run mypy -p tests
      - run: uv run ruff check ./sqla
      - run: uv run ruff check ./tests
